# Generated by Django 4.0.6 on 2022-08-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cronos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobExecution",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("job_id", models.IntegerField(unique=True)),
                ("cron_expression", models.CharField(max_length=32)),
                ("status", models.IntegerField(choices=[], default=0)),
                ("scheduled_start_time", models.DateTimeField(null=True)),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
            ],
        ),
    ]
